version: 2.1

commands:
  install_dependencies:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  build_and_test:
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout
      - install_dependencies
      - run: yarn build
      - run: yarn typecheck
      - run: yarn lint
      - run: yarn test
      - run: yarn format # do it at the very end because test can generate types (which should be formatted)
      - run: yarn check-examples
      - run: yarn no-git-changes # ensure that committed types are up to date

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
